services:
  api:
    build: .
    container_name: order-service-api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      otel-collector:
        condition: service_started
    networks:
      - order-service-network

  postgres:
    image: postgres:16
    container_name: order-service-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - order-service-network

  redis:
    image: redis:7
    container_name: order-service-redis
    ports:
      - '6379:6379'
    networks:
      - order-service-network

  grafana:
    image: grafana/grafana:latest
    container_name: order-service-grafana
    ports:
      - '3001:3000'
    volumes:
      - ./infra/docker/observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - tempo
      - loki
      - alloy
    networks:
      - order-service-network

  tempo:
    image: grafana/tempo:latest
    container_name: order-service-tempo
    command: ['-config.file=/etc/tempo.yml']
    volumes:
      - ./infra/docker/observability/tempo.yml:/etc/tempo.yml:ro
    networks:
      - order-service-network

  loki:
    image: grafana/loki:latest
    container_name: order-service-loki
    command: ['-config.file=/etc/loki/local-config.yaml']
    networks:
      - order-service-network

  alloy:
    image: grafana/alloy:latest
    container_name: order-service-alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    volumes:
      - ./infra/docker/observability/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    networks:
      - order-service-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: order-service-otel-collector
    command: ['--config=/etc/otel-collector.yml']
    ports:
      - '4317:4317'
      - '4318:4318'
    volumes:
      - ./infra/docker/observability/otel-collector.yml:/etc/otel-collector.yml:ro
    depends_on:
      - tempo
      - loki
    networks:
      - order-service-network

volumes:
  postgres-data:

networks:
  order-service-network:
    driver: bridge
